#!/bin/bash

cd /usr/armv7a-unknown-linux-gnueabihf

cp -L /etc/resolv.conf etc/resolv.conf

mkdir -p dev proc sys usr/portage
chown portage:portage usr/portage

mount -t proc none proc
mount --rbind /sys sys
mount --make-rslave sys
mount --rbind /dev dev
mount --make-rslave dev
mount -o bind /usr/portage usr/portage
mount -o bind /usr/local/portage usr/local/portage
mount -t tmpfs none tmp
mount -t tmpfs none var/tmp


# Override some vars defined in sysroot make.conf
export CBUILD=armv7a-unknown-linux-gnueabihf
export FEATURES="-pid-sandbox -network-sandbox"
export ROOT=/
export PKGDIR=/packages/
export PORTAGE_TMPDIR=/tmp/
export PKG_CONFIG_PATH=/usr/lib/pkgconfig/
export PORTDIR_OVERLAY=/usr/local/portage/
chroot . /bin/bash --login

umount var/tmp
umount tmp
umount usr/local/portage
umount usr/portage
umount --recursive dev
umount --recursive sys
umount proc
